---
  tasks:
    - name: hello_task
      classname: HelloTask
      import: demo_worker.tasks
      max_retry: 0
      queue: hello_task

  flows:
    - hello

  storages: []

  global:
    trace:
      - logging: true
        #- json: true
