---
  tasks:
    - name: hello_task
      classname: HelloTask
      import: demo_worker.tasks
      max_retry: 0
      queue: hello_task

    - name: travis_active_repos
      classname: TravisActiveRepos
      import: demo_worker.tasks
      max_retry: 0
      queue: travis_active_repos
      storage: Redis

    - name: travis_repo_builds
      classname: TravisRepoBuilds
      import: demo_worker.tasks
      max_retry: 0
      queue: travis_repo_builds
      storage: Redis

    - name: travis_log_txt
      classname: TravisLogTxt
      import: demo_worker.tasks
      max_retry: 0
      queue: travis_log_txt

  flows:
    - hello
    - travis_repo_logs
    - travis_org_logs

  storages:
  - name: Memory
    classname: InMemoryStorage
    import: selinon.storages.memory
    configuration:
      echo: false

  storages:
  - name: Redis
    classname: Redis
    import: selinon.storages.redis
    configuration:
      host: redis
      port: 6379
      db: 1
      charset: 'utf-8'

  global:
    trace:
      - logging: true
        #- json: true
