---
  tasks:
    - name: hello_task
      queue: hello_task
      classname: HelloTask
      import: demo_worker.tasks
      max_retry: 0

    - name: travis_active_repos_task
      queue: travis_active_repos_task
      classname: TravisActiveRepos
      import: demo_worker.tasks
      max_retry: 0
      storage: Redis

    - name: travis_repo_builds_task
      queue: travis_repo_builds_task
      classname: TravisRepoBuilds
      import: demo_worker.tasks
      max_retry: 0
      storage: Redis

    - name: travis_log_txt_task
      queue: travis_log_txt_task
      classname: TravisLogTxt
      import: demo_worker.tasks
      max_retry: 0
      storage: TravisLogsStorage

  flows:
    - hello
    - travis_repo_logs
    - travis_org_logs
    - travis_build_logs

  storages:
  - name: Memory
    classname: InMemoryStorage
    import: selinon.storages.memory
    configuration:
      echo: false

  - name: Redis
    classname: Redis
    import: selinon.storages.redis
    configuration:
      host: redis
      port: 6379
      db: 1
      charset: 'utf-8'

  - name: TravisLogsStorage
    import: demo_worker.storages
    configuration:
      bucket: 'travis'
      aws_access_key_id: 'PCOMYKL7WQ8ZCESM0TH9'
      aws_secret_access_key: 'aHDakH5CK/5LPM2kDnQX6BAlp9CyIOI9V3E+aU+S'
      region_name: 'us-east-1'
      location: 'us-east-1'
      endpoint_url: 'http://minio:80'
      serialize_json: true

  global:
    trace:
      - logging: true
        #- json: true
