apiVersion: v1
kind: Template
labels:
  template: worker-deploymentconfig
  thoth: 1.0.0
metadata:
  name: worker-deploymentconfig
  annotations:
    description: Selinon API
    openshift.io/display-name: 'Selinon: API'
    version: 1.0.0
    tags: poc,selinon,worker
    template.openshift.io/documentation-url: https://github.com/selinon/
    template.openshift.io/long-description: Selinon worker deployment configuration template.
    template.openshift.io/provider-display-name: Fridolin Pokorny

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: worker
      app: selinon
      component: worker
    name: worker
  spec:
    replicas: 3
    template:
      metadata:
        labels:
          service: worker
      spec:
        containers:
        - env:
          name: worker
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "500m"
              # TODO: readinessProbe:
              # TODO: livenessProbe:
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - worker
        from:
          kind: ImageStreamTag
          name: 'worker:latest'
